// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkateCompScoreboard.Persistence.Data;

#nullable disable

namespace SkateCompScoreboard.Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240222162618_ScoreCompetitor")]
    partial class ScoreCompetitor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkateCompScoreboard.Core.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Acronym")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("SkateCompScoreboard.Core.Entities.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Modality")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PlaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("SkateCompScoreboard.Core.Entities.Competitor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OriginId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OriginId");

                    b.ToTable("Competitors");
                });

            modelBuilder.Entity("SkateCompScoreboard.Core.Entities.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfCompetitors")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfSections")
                        .HasColumnType("int");

                    b.Property<int>("RoundOrder")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("SkateCompScoreboard.Core.Entities.RoundCompetitor", b =>
                {
                    b.Property<Guid>("RoundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetitorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("PodiumOrder")
                        .HasColumnType("int");

                    b.HasKey("RoundId", "CompetitorId");

                    b.HasIndex("CompetitorId");

                    b.ToTable("RoundCompetitors");
                });

            modelBuilder.Entity("SkateCompScoreboard.Core.Entities.Score", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("FinalScore")
                        .HasColumnType("real");

                    b.Property<Guid?>("RoundCompetitorCompetitorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoundCompetitorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RoundCompetitorRoundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrickId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.HasIndex("TrickId");

                    b.HasIndex("RoundCompetitorRoundId", "RoundCompetitorCompetitorId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("SkateCompScoreboard.Core.Entities.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SectionOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoundId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("SkateCompScoreboard.Core.Entities.Trick", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tricks");
                });

            modelBuilder.Entity("SkateCompScoreboard.Core.Entities.LineSection", b =>
                {
                    b.HasBaseType("SkateCompScoreboard.Core.Entities.Section");

                    b.ToTable("LineSections");
                });

            modelBuilder.Entity("SkateCompScoreboard.Core.Entities.SingleTrickSection", b =>
                {
                    b.HasBaseType("SkateCompScoreboard.Core.Entities.Section");

                    b.ToTable("SingleTrickSections");
                });

            modelBuilder.Entity("SkateCompScoreboard.Core.Entities.Competition", b =>
                {
                    b.HasOne("SkateCompScoreboard.Core.Entities.Address", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("SkateCompScoreboard.Core.Entities.Competitor", b =>
                {
                    b.HasOne("SkateCompScoreboard.Core.Entities.Address", "Origin")
                        .WithMany()
                        .HasForeignKey("OriginId");

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("SkateCompScoreboard.Core.Entities.Round", b =>
                {
                    b.HasOne("SkateCompScoreboard.Core.Entities.Competition", "Competition")
                        .WithMany("Rounds")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("SkateCompScoreboard.Core.Entities.RoundCompetitor", b =>
                {
                    b.HasOne("SkateCompScoreboard.Core.Entities.Competitor", "Competitor")
                        .WithMany("Rounds")
                        .HasForeignKey("CompetitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkateCompScoreboard.Core.Entities.Round", "Round")
                        .WithMany("Competitors")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competitor");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("SkateCompScoreboard.Core.Entities.Score", b =>
                {
                    b.HasOne("SkateCompScoreboard.Core.Entities.Section", "Section")
                        .WithMany("Scores")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkateCompScoreboard.Core.Entities.Trick", "Trick")
                        .WithMany()
                        .HasForeignKey("TrickId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkateCompScoreboard.Core.Entities.RoundCompetitor", "RoundCompetitor")
                        .WithMany("Scores")
                        .HasForeignKey("RoundCompetitorRoundId", "RoundCompetitorCompetitorId");

                    b.Navigation("RoundCompetitor");

                    b.Navigation("Section");

                    b.Navigation("Trick");
                });

            modelBuilder.Entity("SkateCompScoreboard.Core.Entities.Section", b =>
                {
                    b.HasOne("SkateCompScoreboard.Core.Entities.Round", "Round")
                        .WithMany("Sections")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("SkateCompScoreboard.Core.Entities.Competition", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("SkateCompScoreboard.Core.Entities.Competitor", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("SkateCompScoreboard.Core.Entities.Round", b =>
                {
                    b.Navigation("Competitors");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("SkateCompScoreboard.Core.Entities.RoundCompetitor", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("SkateCompScoreboard.Core.Entities.Section", b =>
                {
                    b.Navigation("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
